"""Step 7  -  the two advanced LaTeX tables plus a compile proof.

Table 1  Reporting-Delay Atlas   : in-cell data bars + right-edge delay-CDF sparklines
Table 2  Nowcast Scoreboard      : continuous \\cellcolor heatmap shading, paired
                                   naive/nowcast rows, improvement markers

Every printed number is read from a results file; nothing is hand-typed.
Compiles a standalone preview under trbunofficial.cls to prove the tables render;
falls back to data-bars-only (no TikZ) if the sparklines fight the class.

Outputs
  results/tables/tables_preamble.tex, table1.tex, table2.tex,
                 tables_preview.tex, tables_preview.pdf
  results/audits/tables_audit.json
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import figstyle as fs
from common import (AUDIT_DIR, HORIZONS, TAB_DIR, TRB_TEMPLATE_DIR, write_json)

SEV_NAME = {0: "No injury (Y0)", 1: "Crash/fire (Y1)", 2: "Injury (Y2)",
            3: "Fatality (Y3)"}
# VOQ is the vehicle owner's questionnaire itself; the web channel is IVOQ.
# Labels follow NHTSA's published CMPL_TYPE field definitions.
CHAN_NAME = {"IVOQ": "Internet (IVOQ)", "EVOQ": "Hotline (EVOQ)",
             "VOQ": "Questionnaire (VOQ)", "MAVQ": "Mobile app (MAVQ)"}


def esc(s):
    return str(s).replace("%", "\\%").replace("&", "\\&").replace("_", "\\_")


DAY_MAX = 1200.0          # log axis upper bound, just above the largest P90 (1,182 d)
GLYPH_W = "13mm"          # width of the delay-spread glyph column
GLYPH_TICKS = (1, 10, 100, 1000)


def _logx(v):
    """Days -> [0,1] on a log(1+x) axis shared by every row of Table 1."""
    return float(np.clip(np.log10(1.0 + max(float(v), 0.0))
                         / np.log10(1.0 + DAY_MAX), 0.0, 1.0))


def distglyph(p25, p50, p75, p90):
    """Compact box-and-whisker of the delay distribution on a shared log axis.

    Replaces the earlier CDF sparkline, which shared no axis with the numeric
    columns and could not be read row to row. The box spans the quartiles, the
    heavy tick is the median, and the whisker runs to P90, so the glyph is a
    picture of the four numbers printed immediately to its left. Symmetric about
    y = 0 and given a small negative baseline so it centres on the row text.
    """
    a, m, b, w = _logx(p25), _logx(p50), _logx(p75), _logx(p90)
    grid = "".join(f"\\draw[glyphgrid] ({_logx(t):.3f},-1.25) -- ({_logx(t):.3f},1.25);"
                   for t in GLYPH_TICKS)
    return (f"\\begin{{tikzpicture}}[x={GLYPH_W},y=1mm,baseline=-0.75mm]"
            + grid
            + "\\draw[glyphaxis] (0,0) -- (1,0);"
            f"\\draw[whisker] ({b:.3f},0) -- ({w:.3f},0);"
            f"\\draw[whisker] ({w:.3f},-0.62) -- ({w:.3f},0.62);"
            f"\\fill[barfill] ({a:.3f},-0.95) rectangle ({b:.3f},0.95);"
            f"\\draw[medtick] ({m:.3f},-1.25) -- ({m:.3f},1.25);"
            "\\end{tikzpicture}")


def glyph_axis():
    """Header strip for the glyph column: tick labels at their true log positions."""
    labs = {1: "1", 10: "10", 100: "100", 1000: "1k"}
    nodes = "".join(
        f"\\node[anchor=base,inner sep=0pt,font=\\tiny] at ({_logx(t):.3f},0) "
        f"{{{labs[t]}}};" for t in GLYPH_TICKS)
    return (f"\\begin{{tikzpicture}}[x={GLYPH_W},y=1mm,baseline=0mm]"
            + nodes + "\\end{tikzpicture}")


def bar(frac, label):
    return f"\\dbar{{{max(0.0, min(1.0, frac)):.3f}}}{{{label}}}"


def shade(x, vmax):
    """|value| -> (hex background, needs-white-text) on the light-gray->navy ramp."""
    t = float(np.clip(abs(x) / vmax, 0, 1))
    r, g, b, _ = fs.HEATMAP_CMAP(0.08 + 0.92 * t)
    lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    return "%02X%02X%02X" % (round(r * 255), round(g * 255), round(b * 255)), lum < 0.55


# ------------------------------------------------------------------ preamble
PREAMBLE = r"""% Macros for the two advanced tables (generated by analysis/07_tables.py).
% Add these lines to the manuscript preamble, then \input the table files.
\usepackage[table]{xcolor}
\usepackage{booktabs}
\usepackage{tikz}

% ---- in-cell horizontal data bar -------------------------------------------
% \dbar{fraction 0..1}{printed label}
\definecolor{barfill}{HTML}{C9DCEA}
\definecolor{barink}{HTML}{0072B5}
\newlength{\barunit}\setlength{\barunit}{11mm}
\newcommand{\dbar}[2]{%
  \rlap{\textcolor{barfill}{\rule[-0.22em]{\dimexpr#1\barunit\relax}{0.85em}}}%
  \hbox to \barunit{\hspace{0.4em}\footnotesize #2\hfil}}

% ---- delay-CDF sparkline (retained for the fallback layout) ----------------
\tikzset{sparkline/.style={line width=0.35pt,draw=barink,line join=round}}
\tikzset{sparkrule/.style={line width=0.2pt,draw=black!25}}

% ---- delay-spread glyph: quartile box, median tick, whisker to P90 ----------
\tikzset{glyphaxis/.style={line width=0.2pt,draw=black!22}}
\tikzset{glyphgrid/.style={line width=0.15pt,draw=black!12}}
\tikzset{whisker/.style={line width=0.3pt,draw=barink!60}}
\tikzset{medtick/.style={line width=0.75pt,draw=barink,line cap=round}}

% ---- improvement marker -----------------------------------------------------
\definecolor{gainink}{HTML}{0072B5}
\newcommand{\gain}{\textcolor{gainink}{$\blacktriangle$}}
"""

PREAMBLE_FALLBACK = PREAMBLE.replace("\\usepackage{tikz}\n", "") + r"""
% FALLBACK: TikZ sparklines disabled; data bars and cell shading retained.
"""


# ------------------------------------------------------------------ Table 1
def table1(use_tikz=True):
    q = pd.read_csv(os.path.join(TAB_DIR, "delay_quantiles.csv"))
    ec_s = pd.read_csv(os.path.join(TAB_DIR, "ecdf_by_severity.csv"))
    ec_c = pd.read_csv(os.path.join(TAB_DIR, "ecdf_by_channel.csv"))
    ec_e = pd.read_csv(os.path.join(TAB_DIR, "ecdf_by_era.csv"))

    def F_sev(s):
        g = ec_s[ec_s.severity == s].sort_values("d")
        return g["F"].to_numpy(), int(g["n"].iloc[0])

    def F_all():
        Fs, ns = [], []
        for s in sorted(ec_s.severity.unique()):
            f, n = F_sev(s)
            Fs.append(f * n); ns.append(n)
        return np.sum(Fs, axis=0) / sum(ns), sum(ns)

    def F_lvl(df, col, lvl):
        g = df[df[col].astype(str) == str(lvl)].sort_values("d")
        return (g["F"].to_numpy(), int(g["n"].iloc[0])) if len(g) else (None, 0)

    n_total = int(q[q.group == "overall"]["n"].iloc[0])
    rows = []

    def add(label, qrow, F, indent=False):
        if qrow is None or F is None:
            return
        nm = f"\\hspace{{0.8em}}{esc(label)}" if indent else f"\\textbf{{{esc(label)}}}"
        cells = [nm, f"{int(qrow['n']):,}".replace(",", "\\,"),
                 f"{100 * qrow['n'] / n_total:.1f}"]
        cells += [f"{qrow[k]:,.0f}".replace(",", "\\,")
                  for k in ("p25", "p50", "p75", "p90")]
        cells += [bar(F[h], f"{100 * F[h]:.0f}") for h in (1, 6, 12)]
        cells.append(distglyph(qrow["p25"], qrow["p50"], qrow["p75"], qrow["p90"])
                     if use_tikz else "")
        rows.append(" & ".join(cells) + r" \\")

    Fa, _ = F_all()
    add("All consumer complaints", q[q.group == "overall"].iloc[0], Fa)
    rows.append(r"\addlinespace[2pt]")
    rows.append(r"\multicolumn{11}{@{}l}{\textit{By severity class}}\\")
    for s in range(4):
        F, _ = F_sev(s)
        sub = q[(q.group == "severity") & (q.level.str.startswith(f"Y{s}"))]
        if len(sub):
            add(SEV_NAME[s], sub.iloc[0], F, indent=True)

    rows.append(r"\addlinespace[2pt]")
    rows.append(r"\multicolumn{11}{@{}l}{\textit{By reporting channel}}\\")
    for ch in ("IVOQ", "EVOQ", "VOQ", "MAVQ"):
        sub = q[(q.group == "channel") & (q.level == ch)]
        F, _ = F_lvl(ec_c, "channel", ch)
        if len(sub) and F is not None:
            add(CHAN_NAME[ch], sub.iloc[0], F, indent=True)

    rows.append(r"\addlinespace[2pt]")
    rows.append(r"\multicolumn{11}{@{}l}{\textit{By incident-cohort era}}\\")
    for era in ("1995-2004", "2005-2014", "2015-2023"):
        sub = q[(q.group == "era") & (q.level == era)]
        F, _ = F_lvl(ec_e, "era", era)
        if len(sub) and F is not None:
            add(era.replace("-", "--"), sub.iloc[0], F, indent=True)

    spark_col = "l" if use_tikz else ""
    spark_hdr = (r" & \multicolumn{1}{c}{\footnotesize Delay spread}" if use_tikz else "")
    spark_sub = (r" & \multicolumn{1}{c}{" + glyph_axis() + "}") if use_tikz else ""
    body = "\n".join(rows)
    return rf"""% Table 1  -  Reporting-Delay Atlas. Generated by analysis/07_tables.py.
% Requires tables_preamble.tex.
\begin{{table}}[!ht]
\caption{{Reporting-Delay Atlas: complaint counts, delay quantiles and reported-by
horizons for consumer-channel complaints, mature incident cohorts only
($t \leq$ 2023-06 $= T - D$). Shaded bars show the share reported within
1, 6 and 12 months; {'the right-hand sparkline traces the full delay CDF $F(d)$, $d = 0$--36 months' if use_tikz else 'delay CDFs are shown in Figure 2a'}.}}
\label{{tab:atlas}}
\footnotesize
\centering
\begin{{tabular}}{{@{{}}l r r r r r r l l l {spark_col}@{{}}}}
\toprule
 & & & \multicolumn{{4}}{{c}}{{Delay (days)}} & \multicolumn{{3}}{{c}}{{Reported within}} {spark_hdr}\\
\cmidrule(lr){{4-7}}\cmidrule(lr){{8-10}}
Group & $N$ & \% & P25 & P50 & P75 & P90 & 1 mo & 6 mo & 12 mo {spark_sub}\\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


# ------------------------------------------------------------------ Table 2
def table2():
    m = pd.read_csv(os.path.join(AUDIT_DIR, "backtest_metrics.csv"))
    m = m[m["origin_set"].str.startswith("evaluation")]
    streams = ["Y0", "Y1", "Y2", "Y3", "severe"]
    name = {"Y0": "No injury (Y0)", "Y1": "Crash/fire (Y1)", "Y2": "Injury (Y2)",
            "Y3": "Fatality (Y3)", "severe": "All severe (Y$\\geq$1)"}
    vmax = float(m[m.method == "naive"]["rel_bias"].abs().max())

    label = {"naive": "naive", "onestep": "one-step", "nowcast": "chain ladder"}
    rows = []
    for s in streams:
        for method in ("naive", "onestep", "nowcast"):
            cells = []
            for h in HORIZONS:
                r = m[(m.stream == s) & (m.h == h) & (m.method == method)]
                if not len(r):
                    cells.append("--")
                    continue
                b = float(r["rel_bias"].iloc[0])
                hexc, white = shade(b, vmax)
                txt = f"{100 * b:+.1f}"
                if method == "nowcast":
                    # marker now means: beats BOTH comparators on |bias|
                    o = m[(m.stream == s) & (m.h == h) & (m.method == "naive")]
                    o1 = m[(m.stream == s) & (m.h == h) & (m.method == "onestep")]
                    better = (len(o) and abs(b) < abs(float(o["rel_bias"].iloc[0]))
                              and len(o1) and abs(b) < abs(float(o1["rel_bias"].iloc[0])))
                    mark = r"\,\gain" if better else ""
                    cov = float(r["cov90"].iloc[0])
                    inner = (rf"{txt}{mark}\\[-1pt]{{\tiny {100 * cov:.0f}\%}}")
                else:
                    # single-height row: only the chain-ladder row carries a coverage
                    # sub-line, so the phantom that used to pad these rows is dropped
                    inner = txt
                col = r"\color{white}" if white else ""
                cells.append(rf"\cellcolor[HTML]{{{hexc}}}{{{col}\shortstack{{{inner}}}}}")
            lab = (rf"\multirow{{3}}{{*}}{{{name[s]}}} & {label[method]}"
                   if method == "naive" else rf" & {label[method]}")
            rows.append(lab + " & " + " & ".join(cells) + r" \\")
        rows.append(r"\addlinespace[1.5pt]")

    body = "\n".join(rows[:-1])
    hdr = " & ".join(rf"\multicolumn{{1}}{{c}}{{$h={h}$}}" for h in HORIZONS)
    return rf"""% Table 2  -  Nowcast Scoreboard. Generated by analysis/07_tables.py.
% Requires tables_preamble.tex and \usepackage{{multirow}}.
\begin{{table}}[!ht]
\caption{{Nowcast Scoreboard: mean relative bias (\%) against the realized
delay-capped cohort total $C_s(t,D)$, by severity stream and horizon $h$ (months
since the incident month), on held-out backtest origins 2021-01--2023-06.
Background shading is proportional to $|$bias$|$ (light $=$ accurate).
\gain\ marks horizons where the delay-corrected nowcast beats the naive count.
The small numbers under the nowcast rows are empirical 90\% interval coverage.}}
\label{{tab:scoreboard}}
\footnotesize
\centering
\begin{{tabular}}{{@{{}}l l ccccc@{{}}}}
\toprule
Severity stream & Method & {hdr} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


# ------------------------------------------------------------------ compile
PREVIEW = r"""\documentclass[]{trbunofficial}
\usepackage{multirow}
\input{tables_preamble}
\AuthorHeaders{Nowcasting}
\title{Table render proof}
\begin{document}
\nolinenumbers
\input{table1}
\clearpage
\input{table2}
\end{document}
"""


def compile_preview():
    tex = os.path.join(TAB_DIR, "tables_preview.tex")
    with open(tex, "w", encoding="utf-8") as fh:
        fh.write(PREVIEW)
    cmd = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
           f"-include-directory={TRB_TEMPLATE_DIR}", "tables_preview.tex"]
    log = ""
    for _ in range(2):
        p = subprocess.run(cmd, cwd=TAB_DIR, capture_output=True, text=True,
                           errors="replace")
        log = p.stdout + p.stderr
    ok = os.path.exists(os.path.join(TAB_DIR, "tables_preview.pdf")) and p.returncode == 0
    return ok, log


def write_all(use_tikz):
    with open(os.path.join(TAB_DIR, "tables_preamble.tex"), "w", encoding="utf-8") as fh:
        fh.write(PREAMBLE if use_tikz else PREAMBLE_FALLBACK)
    with open(os.path.join(TAB_DIR, "table1.tex"), "w", encoding="utf-8") as fh:
        fh.write(table1(use_tikz=use_tikz))
    with open(os.path.join(TAB_DIR, "table2.tex"), "w", encoding="utf-8") as fh:
        fh.write(table2())


def main():
    audit = {}
    for attempt, use_tikz in ((1, True), (2, False)):
        write_all(use_tikz)
        ok, log = compile_preview()
        audit[f"attempt_{attempt}"] = {
            "sparklines_tikz": use_tikz, "compiled": bool(ok),
            "errors": [l for l in log.splitlines()
                       if l.startswith("!") or "Overfull" in l][:12],
        }
        print(f"  attempt {attempt} (tikz sparklines={use_tikz}): "
              f"{'COMPILED' if ok else 'FAILED'}")
        if ok:
            audit["final"] = {"sparklines": use_tikz,
                              "fallback_used": not use_tikz,
                              "pdf": "results/tables/tables_preview.pdf"}
            break
    else:
        raise SystemExit("both table variants failed to compile  -  see log above")

    for junk in ("tables_preview.aux", "tables_preview.log", "tables_preview.out"):
        p = os.path.join(TAB_DIR, junk)
        if os.path.exists(p):
            os.remove(p)
    write_json(os.path.join(AUDIT_DIR, "tables_audit.json"), audit)
    print(f"  tables written; sparklines={'ON' if audit['final']['sparklines'] else 'OFF'}")


if __name__ == "__main__":
    main()
